name: Flask SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download SonarQube Scanner
        run: curl -OL https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472.zip && unzip sonar-scanner-cli-4.6.2.2472.zip

 #     - name: Run Unit Tests
 #       run: python -m unittest discover tests/

      - name: Debug Environment Variables
        run: |
         echo "SONAR_LOGIN: $SONAR_LOGIN"
         echo "SONAR_HOST_URL: $SONAR_HOST_URL"


      - name: Configure SonarQube
        run: echo "sonar.host.url=$SONAR_HOST_URL" >> /home/runner/work/Python-POC/Python-POC/sonar-scanner-4.6.2.2472/conf/sonar-scanner.properties

      - name: SonarQube Analysis
        run: sonar-scanner-4.6.2.2472/bin/sonar-scanner -Dsonar.projectKey=my-project -Dsonar.sources=. -Dsonar.login=$SONAR_LOGIN
        env:
          SONAR_LOGIN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
