name: CI

on:
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint with flake8
        run: |
         pip install flake8
         # stop the build if there are Python syntax errors or undefined names
         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics


      - name: Run Unit Tests
        run: python -m unittest discover tests/
        
      
      - name: Set Up SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
         SONAR_ORGANIZATION: cloudsq
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         SONAR_PROJECT_KEY: bmw
          
      - name: Run SonarCloud Analysis
        run: sonar-scanner

      - name: Build Docker Image
        run: docker build -t my-flask-app .
        
      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.deb
          sudo dpkg -i trivy_0.18.3_Linux-64bit.deb
          
      - name: Run Trivy on Docker Image
        run: trivy image my-flask-app
