name: CI

on:
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint with flake8
        run: |
         pip install flake8
         # stop the build if there are Python syntax errors or undefined names
         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics


      - name: Run Unit Tests
        run: python -m unittest discover tests/

      
      - name: Set Up SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
         SONAR_ORGANIZATION: "cloudsq"
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
     
          
      - name: Run SonarCloud Analysis
        run: sonar-scanner

