name: CI

on:
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint with flake8
        run: |
         pip install flake8
         # stop the build if there are Python syntax errors or undefined names
         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
         pip install pytest
         pytest

      - name: Download SonarQube Scanner
        run: curl -OL https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472.zip && unzip sonar-scanner-cli-4.6.2.2472.zip

      - name: Run Unit Tests
        run: python -m unittest discover tests/



      - name: Configure SonarQube
        run: echo "sonar.host.url=$SONAR_HOST_URL" >> /home/runner/work/Python-POC/Python-POC/sonar-scanner-4.6.2.2472/conf/sonar-scanner.properties

      - name: SonarQube Analysis
        run: sonar-scanner-4.6.2.2472/bin/sonar-scanner -X -Dsonar.projectKey=bmw-devops -Dsonar.sources=. -Dsonar.login=sqp_590f3f2373320e9927fe9be8dd7f8078e3395e96
        env:
          SONAR_LOGIN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
